CropResizer:
  x_max: 420
  x_min: 187
  y_max: 534
  y_min: 107
GaussianBlurFilter:
  kernel_width: 0
HSVLogicalFilter:
  h_max: 255
  h_min: 0
  s_max: 255
  s_min: 0
  v_max: 255
  v_min: 0
ResolutionChangeResizer:
  resol: 224
